### PR TITLE
Add diagnostics publication on frequency and status

### PR DESCRIPTION
**Pull request by romainreignier**
And do not publish in Wait for Position because orientation is identity quaternion.

### CODE REVIEW

**Comment by romainreignier** [comment]
Must wait for https://github.com/ixblue/ixblue_stdbin_decoder/pull/5 to be merged and released for the buildfarm to find the dependency.

**Comment by romainreignier** [comment]
@ros-pull-request-builder retest this please

**Comment by romainreignier** [comment]
Buildfarm ok:
- http://build.ros.org/job/Mpr__ixblue_ins_stdbin_driver__ubuntu_bionic_amd64/
- http://build.ros.org/job/Npr__ixblue_ins_stdbin_driver__ubuntu_focal_amd64/

**Review by adrienbarral — APPROVED** [review]
The rosPublisher is becomming quite big, maybe it would be good to create a "Diagnostics Publisher" class that we can compose in the ros_publisher. We can put in this class every things related to diagnostics. I think that can reduce size of the ros_publisher file by 100 lines of code.

**Comment by romainreignier** [comment]
Thanks @adrienbarral I have made the mentioned changes, added a disconnection detection and tried on a real unit.

**Pull request merged**
